name: Count Lines of Code in Repository

on: [push]

jobs:
  count-python-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Count lines of code
      run: |
        echo "Repository contains $(find . -name '*.py' | xargs wc -l) lines of code."